Submission page
ntut-xuan/NuOJ pull request #78
Opened 2023-03-23 14:43 UTC by Ponywen0819

在這份PR中我做了以下的事情
-  將problem_list 中 react.js 舊版本掛載方式更換成新方法
-  將UerInfo 部件獨立
-  開發了Table部件 可以在所有有表格的情況下使用
- 完成沒有API的submission page

2023-04-01 07:45 UTC, ntut-xuan requested changes
後端似乎不小心被改到了，請 revert 回去

2023-04-01 07:45 UTC, ntut-xuan commented on python/app.py
如果是從前端的 branch 分出去的話，不應該改到後端的 code，你得要後端開一個 branch 去更改這些改動。

2023-04-01 07:45 UTC, ntut-xuan commented on python/page/submission/__init__.py
如果是從前端的 branch 分出去的話，不應該改到後端的 code，你得要後端開一個 branch 去更改這些改動。

2023-04-01 07:45 UTC, ntut-xuan commented on python/page/submission/route.py
如果是從前端的 branch 分出去的話，不應該改到後端的 code，你得要後端開一個 branch 去更改這些改動。

2023-04-01 07:45 UTC, ntut-xuan commented on dockerfile
Dockerfile 的改動在後端的 branch 開 PR 會比較適合。

2023-04-03 14:29 UTC, Ponywen0819 commented
已將後段變更還原！

2023-04-08 18:32 UTC, ntut-xuan requested changes
做了一點功能性與排版的建議，請修改。

另外，額外請確認這幾件事情：
 1. 文字的顏色似乎是灰色的，但正常的情況下應該是白色
 2. 對於這類的 scoreboard，我認為使用等寬字體會比較好

2023-04-08 18:32 UTC, ntut-xuan commented on src/js/submission_list.jsx
> +            {lable: '提交ID', id: 'id', width: '6rem'},
根據中文排版指北，建議修改為「提交 ID」

2023-04-08 18:32 UTC, ntut-xuan commented on src/js/submission_list.jsx
> +            {lable: '時長', id: 'consume_time'}
時長的意義似乎不是分鐘跟秒鐘，是毫秒（例如 1024ms）。

2023-04-08 18:32 UTC, ntut-xuan commented on src/js/submission_list.jsx
> +                    {data.map(row=>Column({ids: ids,config: config,data: row}))}
我認為表格的高度似乎有點太窄了，高度加點 padding 會更好看（建議加個 `py-5`）

2023-06-17 08:18 UTC, Ponywen0819 commented
由於架構有變更，因此將此 PR 關閉！

2023-06-17 08:19 UTC, Ponywen0819 commented
由於架構有變更，因此將此 PR 關閉！

2023-06-17 08:19 UTC, closed without merging