Create necessary config
ntut-xuan/NuOJ pull request #80
Opened 2023-04-07 09:12 UTC by Ponywen0819

這份PR中做了下列變更：
- 使用package.json 紀錄所需套件
- 使用webpack 做babel 轉譯 與 程序碼打包
- 利用webpack 建置開發伺服器 使前端開發不需實體伺服器介入
- 建置mock環境 使API介接更為順利

2023-04-07 09:17 UTC, ntut-xuan commented
預期怎麼使用呢，可以提供看看使用的步驟

2023-04-07 14:10 UTC, Ponywen0819 commented
在開發過程中可以使用```npm run dev-server``` 來啟用開發伺服器，並根據設定檔內entry轉譯程式碼

如開發環境被設定成development，則會將msw一起進行打包，如此就可以依據設定的API進行模擬

2023-05-31 14:14 UTC, ntut-xuan commented on dockerfile
> +RUN npm install
可以考慮使用 PnPm(https://pnpm.io/zh-TW/)

```suggestion
RUN npm install -g pnpm
```

2023-05-31 14:16 UTC, ntut-xuan commented on dockerfile
> +RUN npm install
可以考慮用 [PnPm](https://pnpm.io/)

```suggestion
RUN npm install pnpm
```

2023-05-31 14:22 UTC, ntut-xuan requested changes

2023-05-31 14:22 UTC, ntut-xuan commented on dockerfile
> +RUN npx msw init src/js --save
可以考慮使用 [pnpm](https://pnpm.io/zh-TW/)

```suggestion
RUN npm install pnpm
RUN pnpm install 
RUN npx msw init src/js --save
```

2023-06-07 01:08 UTC, Ponywen0819 commented
由於現在的前端開發環境與後端的執行環境混合在 docker 中，導致前端開發時必須同時也啟動後端服務，因此此變更不適用。

前端開發環境會使用另外一個 PR ，此 PR 目的轉為將前端開發環境從 docker 也就是後端環境去除。

2023-06-07 11:50 UTC, closed without merging